"""Build the reviewer-facing Stage-1 metrics artifact and LaTeX macros."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAIN_RUN = ROOT / "eval/results/runs/p7-screening-model-corrected-20260912-r2/metrics.json"
NEAR_RUN = ROOT / "eval/results/runs/p7-near-negative-20260912-r1/paired_metrics.json"


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build() -> dict:
    main = json.loads(MAIN_RUN.read_text(encoding="utf-8"))
    near = json.loads(NEAR_RUN.read_text(encoding="utf-8"))
    operating = main["metrics"]["0.01"]
    near_data = near["near_negative"]
    near_operating = near_data["metrics"]["0.01"]
    result = {
        "schema_version": 1,
        "source_commit": "a8f8a5f",
        "evaluation_artifact_sha256": sha256_file(MAIN_RUN),
        "near_negative_artifact_sha256": sha256_file(NEAR_RUN),
        "main": {
            "tp": operating["tp"], "fp": operating["fp"],
            "tn": main["partition_labels"]["test"]["benign"] - operating["fp"],
            "fn": main["partition_labels"]["test"]["attack"] - operating["tp"],
            "precision": operating["precision"], "recall": operating["recall"],
            "fpr": operating["realized_fpr"], "auprc": main["metrics"]["auc_pr"],
            "positive_denominator": main["partition_labels"]["test"]["attack"],
            "negative_denominator": main["partition_labels"]["test"]["benign"],
            "threshold": operating["threshold"],
        },
        "structural_near_negative": {
            "tp": near_operating["tp"], "fp": near_operating["fp"],
            "negative_denominator": near_data["n_negative"],
            "precision": near_operating["precision"],
            "recall": near_operating["recall"],
            "fpr": near_operating["realized_fpr"],
            "auprc": near_data["metrics"]["auc_pr"],
            "threshold": near_operating["threshold"],
            "status": "diagnostic; hard-negative adjudication pending",
        },
        "lineage": {
            "main_artifact": str(MAIN_RUN.relative_to(ROOT)),
            "near_negative_artifact": str(NEAR_RUN.relative_to(ROOT)),
            "threshold_definition": "1% calibration target; held-out realized FPR",
            "claim": "Stage 1 prioritization/ranking, not standalone causal classification",
        },
    }
    return result


def macros(metrics: dict) -> str:
    main = metrics["main"]
    near = metrics["structural_near_negative"]
    return """%% Generated by tools/build_paper_metrics.py; do not edit.
\\newcommand{\\StageOneAUPRC}{%.6f}
\\newcommand{\\StageOnePrecision}{%.4f}
\\newcommand{\\StageOneRecall}{%.4f}
\\newcommand{\\StageOneFPR}{%.2f\\%%}
\\newcommand{\\StageOneTP}{%d}
\\newcommand{\\StageOneFP}{%d}
\\newcommand{\\StageOneNegatives}{%d}
\\newcommand{\\NearNegativeAUPRC}{%.6f}
\\newcommand{\\NearNegativeFPR}{%.2f\\%%}
\\newcommand{\\NearNegativeFP}{%d}
\\newcommand{\\NearNegativeN}{%d}
""" % (
        main["auprc"], main["precision"], main["recall"], main["fpr"] * 100,
        main["tp"], main["fp"], main["negative_denominator"], near["auprc"],
        near["fpr"] * 100, near["fp"], near["negative_denominator"])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "eval/results/paper_metrics.json")
    parser.add_argument("--tex-output", type=Path, default=ROOT / "paper/generated_metrics.tex")
    args = parser.parse_args()
    metrics = build()
    args.output.write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    args.tex_output.write_text(macros(metrics), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
